#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MarketForge PRO
Participant Master Append Pipeline (Historical Destination Mode)
Path(r"H:/MarketForge/data/processed/participant_historical/participant_master.csv")
"""

import pandas as pd
from pathlib import Path

print("📂 INITIALIZING PARTICIPANT HISTORICAL MASTER APPENDER...\n")

# CONFIGURATION - Routing to historical destination directories
CLEAN_DAILY_DIR      = Path(r"H:/MarketForge/data/processed/participant_daily")
HISTORICAL_CLEAN_DIR = Path(r"H:/MarketForge/data/historical/participant_historical")
MASTER_FILE          = HISTORICAL_CLEAN_DIR / "participant_master.csv"

HISTORICAL_CLEAN_DIR.mkdir(parents=True, exist_ok=True)

# 1. Automatically grab the newest daily file generated by your cleaner script
all_daily_files = sorted(list(CLEAN_DAILY_DIR.glob("participant_clean_*.csv")))

if not all_daily_files:
    print(f"❌ Aborting: No clean daily snapshots found in '{CLEAN_DAILY_DIR}'. Run daily cleaner first.")
    exit()

daily_clean_file = all_daily_files[-1]
print(f"📋 Found newest processed daily file on disk: {daily_clean_file.name}")

daily_df = pd.read_csv(daily_clean_file)

# 2. Check if the historical master tracker file already exists
if MASTER_FILE.exists():
    try:
        master_df = pd.read_csv(MASTER_FILE)
        print(f"  📊 Loaded existing historical registry database master ({len(master_df)} rows).")
    except Exception:
        print("  ⚠️ Master database file corrupted or unreadable. Initializing a clean base template.")
        master_df = pd.DataFrame()
else:
    print("  ℹ️ Historical master file not found. Building a fresh tracking structure.")
    master_df = pd.DataFrame()

# 3. Combine databases cleanly
updated_master = pd.concat([master_df, daily_df], ignore_index=True)

# 4. Multi-index deduplication to safely support row-stacked VOLUME and OI elements
updated_master = updated_master.drop_duplicates(subset=["date", "data_type", "client_type"], keep="last")

# 5. Enforce integer constraints on metric targets across combined arrays
numeric_cols = [
    "future_index_long", "future_index_short", "net_index_futures",
    "future_stock_long", "future_stock_short", "net_stock_futures",
    "option_index_call_long", "option_index_put_long", 
    "option_index_call_short", "option_index_put_short", "net_index_options",
    "total_long_contracts", "total_short_contracts", "net_total"
]

for col in numeric_cols:
    if col in updated_master.columns:
        updated_master[col] = pd.to_numeric(updated_master[col], errors="coerce").fillna(0).astype(int)

# 6. Sort logically to keep timestamps, data tracking modes, and market profiles structured
updated_master = updated_master.sort_values(["date", "data_type", "client_type"]).reset_index(drop=True)

# 7. Write clean structured array matrix back to target master storage block
updated_master.to_csv(MASTER_FILE, index=False)

print(f"\n🚀 Historical file successfully synchronized! Current Row Count: {len(updated_master)}")
print(f"📁 Destination Path: {MASTER_FILE}")